// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATXJrPAT6Kd_9VQEXCnNmaXsSsTZaiWIY',
    appId: '1:973890908256:android:cf4b352c02147d0a545305',
    messagingSenderId: '973890908256',
    projectId: 'cinematy-app',
    storageBucket: 'cinematy-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28m_EpNFl-34qOEeWB7snYMKYuK-mmns',
    appId: '1:973890908256:ios:bfc5068322f9cf26545305',
    messagingSenderId: '973890908256',
    projectId: 'cinematy-app',
    storageBucket: 'cinematy-app.firebasestorage.app',
    androidClientId: '973890908256-ee3nm882sppk8t6kt0vd0gp3i1rk2ppc.apps.googleusercontent.com',
    iosClientId: '973890908256-7jgno3lov2klrfiei0n50o1ju1l1vto2.apps.googleusercontent.com',
    iosBundleId: 'com.cinematy.app',
  );
}
